spring:
  application:
    name: sec-lab1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #${JDBC-URL}
    username: postgres #${JDBC-USER}
    password: postgres #${JDBC-PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  token:
    signing-key: b936cee86c9f87aa5d3c6f2e84cb5a4239a5fe50480a6ec66b70ab5b1f4ac6730c6c515421b327ec1d69402e53dfb49ad7381eb067b338fd7b0cb22247225d47 #${TOKEN-SIGNING-KEY}
    tll-seconds: 600